---
title: Python核心概念之异常处理
tags:
  - Python3
categories:
  - Python
---
和其他语言一样，异常处理是 Python 中一种很常见，并且很重要的机制与代码规范。

在开始之前，首先要先了解清楚Python中的错误和异常都是什么,两者之间有什么区别和联系

### 错误与异常

通常来说，程序中的错误至少包括两种，一种是语法错误，另一种则是异常。

所谓语法错误，也就是你写的代码不符合编程规范，无法被识别与执行，比如下面这个例子：

```python
if name is not None
    print(name)
```

If 语句漏掉了冒号，不符合 Python 的语法规范，所以程序就会报错invalid syntax.

而异常则是指程序的语法正确，也可以被执行，但在执行过程中遇到了错误，抛出了异常，比如下面的 3 个例子：

```python
10 / 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
    
order * 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'order' is not defined

1 + [1,2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'int' and 'list'
```

它们语法完全正确，但显然，我不能做除法时让分母为 0；也不能使用未定义的变量做运算；而让一个整型和一个列表相加也是不可取的。于是，当程序运行到这些地方时，就抛出了异常，并且终止运行。例子中的ZeroDivisionError NameError和TypeError，就是三种常见的异常类型。

Python 中还有很多其他异常类型，比如KeyError是指字典中的键找不到；FileNotFoundError是指发送了读取文件的请求，但相应的文件不存在等等。文章中不在赘述，详情参考 [相关文档](https://docs.python.org/3/library/exceptions.html#bltin-exceptions)

### 处理异常

#### try except语句

异常处理，通常使用 try 和 except 来解决，比如：

```python
try:
    s = input('please enter two numbers separated by comma: ')
    num1 = int(s.split(',')[0].strip())
    num2 = int(s.split(',')[1].strip())
    ... 
except ValueError as err:
    print('Value Error: {}'.format(err))

print('continue')
...
```

这里默认用户输入以逗号相隔的两个整形数字，将其提取后，做后续的操作

如果输入a,b，程序便会抛出异常invalid literal for int() with base 10: 'a'，然后跳出 try 这个 block。

由于程序抛出的异常类型是 ValueError，和 except block 所 catch 的异常类型相匹配，所以 except block 便会被执行，最终输出Value Error: invalid literal for int() with base 10: 'a'，并打印出continue

```python
please enter two numbers separated by comma: a,b
Value Error: invalid literal for int() with base 10: 'a'
continue
```

except block 只接受与它相匹配的异常类型并执行，如果程序抛出的异常并不匹配，那么程序照样会终止并退出。所以，还是刚刚这个例子，如果只输入1，程序抛出的异常就是IndexError: list index out of range，与 ValueError 不匹配，那么 except block 就不会被执行，程序便会终止并退出（continue 不会被打印）。

```python
please enter two numbers separated by comma: 1
Traceback (most recent call last):
  File "l8.py", line 5, in <module>
    num2 = int(s.split(',')[1].strip())
IndexError: list index out of range
```

很显然，这样强调一种类型的写法有很大的局限性，我们可以在except block接收多种异常类型，比如:

```python
try:
    s = input('please enter two numbers separated by comma: ')
    num1 = int(s.split(',')[0].strip())
    num2 = int(s.split(',')[1].strip())
    ...
except (ValueError, IndexError) as err:
    print('Error: {}'.format(err))
    
print('continue')
...
```

或者第二种写法:

```python
try:
    s = input('please enter two numbers separated by comma: ')
    num1 = int(s.split(',')[0].strip())
    num2 = int(s.split(',')[1].strip())
    ...
except ValueError as err:
    print('Value Error: {}'.format(err))
except IndexError as err:
    print('Index Error: {}'.format(err))

print('continue')
...
```

这样，每次程序执行时，except block 中只要有一个 exception 类型与实际匹配即可。

不过很多时候，很难保证程序覆盖到所有的异常类型，所以更通常的做法是在**最后一个 except block，声明其处理的异常类型是 Exception。Exception 是其他所有非系统异常的基类，能够匹配任意非系统异常。**那么这段代码就可以写成下面这样：

```python
try:
    s = input('please enter two numbers separated by comma: ')
    num1 = int(s.split(',')[0].strip())
    num2 = int(s.split(',')[1].strip())
    ...
except ValueError as err:
    print('Value Error: {}'.format(err))
except IndexError as err:
    print('Index Error: {}'.format(err))
except Exception as err:
    print('Other error: {}'.format(err))

print('continue')
...
```

或者，也可以在 except 后面省略异常类型，这表示与任意异常相匹配（包括系统异常等）：

```python
try:
    s = input('please enter two numbers separated by comma: ')
    num1 = int(s.split(',')[0].strip())
    num2 = int(s.split(',')[1].strip())
    ...
except ValueError as err:
    print('Value Error: {}'.format(err))
except IndexError as err:
    print('Index Error: {}'.format(err))
except:
    print('Other error')

print('continue')
...
```

需要注意，当程序中存在多个 except block 时，最多只有一个 except block 会被执行。换句话说，如果多个 except 声明的异常类型都与实际相匹配，那么只有最前面的 except block 会被执行，其他则被忽略

#### finally

异常处理中，还有一个很常见的用法是 finally，经常和 try、except 放在一起来用。无论发生什么情况，finally block 中的语句都会被执行，哪怕前面的 try 和 excep block 中使用了 return 语句。

一个常见的应用场景，便是文件的读取:

```python
import sys
try:
    f = open('file.txt', 'r')
    .... # some data processing
except OSError as err:
    print('OS error: {}'.format(err))
except:
    print('Unexpected error:', sys.exc_info()[0])
finally:
    f.close()
```

这段代码中，try block 尝试读取 file.txt 这个文件，并对其中的数据进行一系列的处理，到最后，无论是读取成功还是读取失败，程序都会执行 finally 中的语句——关闭这个文件流，确保文件的完整性。因此，在 finally 中，我们通常会放一些无论如何都要执行的语句。

### 自定义异常

前面的例子里充斥了很多 Python 内置的异常类型,同时Python也允许用户自定义异常类型

下面这个例子，创建了自定义的异常类型 MyInputError，定义并实现了初始化函数和 str 函数（直接 print 时调用）

```python
class MyInputError(Exception):
    """Exception raised when there're error in input"""
    def __init__(self,value):
        self.value = value
    
    def __str__(self):
        return("{} is invalid input".format(repr(self.value)))

try:
    raise MyInputError(1):
except MyInputError as err:
    print("error: {}".format(err))
```

执行上述代码块并输出，便会得到下面的结果：

```python
error: 1 is invalid input
```

际工作中，如果内置的异常类型无法满足我们的需求，或者为了让异常更加详细、可读，想增加一些异常类型的其他功能，我们可以自定义所需异常类型。不过，大多数情况下，Python 内置的异常类型就足够好了



### 总结

- 异常，通常是指程序运行的过程中遇到了错误，终止并退出。我们通常使用 try except 语句去处理异常，这样程序就不会被终止，仍能继续执行。
- 处理异常时，如果有必须执行的语句，比如文件打开后必须关闭等等，则可以放在 finally block 中。
- 异常处理，通常用在你不确定某段代码能否成功执行，也无法轻易判断的情况下，比如数据库的连接、读取等等。正常的 flow-control 逻辑，不要使用异常处理，直接用条件语句解决就可以了。

